import { Footer } from '@/components/Footer'
import { Header } from '@/components/Header'
import type { Metadata } from 'next'
import { Lato, Montserrat } from 'next/font/google'
import './globals.css'

const lato = Lato({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-lato',
})

const montserrat = Montserrat({
  subsets: ['latin'],
  weight: '400',
  variable: '--font-montserrat',
})

export const metadata: Metadata = {
  title: 'Trova Brasil',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-br" className={`${lato.variable} ${montserrat.variable}`}>
      <body className={lato.className}>
        <div className="m-0 flex h-dvh w-screen flex-col items-center gap-y-20 p-0">
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  )
}
